### PR TITLE
Swagger specification added

### PR DESCRIPTION
**Pull request by qandeelarshad**
Added the swagger specification file for SwaggerUI documentation. Swagger UI can be viewed on localhost:5000/swagger.

### CODE REVIEW

**Review by AbdulSir — APPROVED** [review]
I have reviewed this PR. It was only missing the dependency to be added in the package.json so it can be installed automatically when we run `npm install`
It is generating the report we are expecting I approve.

**Review by purplesmurf1998 — CHANGES_REQUESTED** [review]
The API specification looks great and is handy since it will remain up to date with the new controllers and endpoints. Can you also look into [pikturr](https://github.com/nrekretep/pikturr)? It uses the swagger url to generate a class diagram for our API. That combined with the specification would be enough for the API documentation

**Comment by qandeelarshad** [comment]
> The API specification looks great and is handy since it will remain up to date with the new controllers and endpoints. Can you also look into [pikturr](https://github.com/nrekretep/pikturr)? It uses the swagger url to generate a class diagram for our API. That combined with the specification would be enough for the API documentation
> 
> I've marked as "Request changes" for the pikturr implementation. The swagger implementation looks good and I have nothing to change.

Sure, I'll look into pikturr. I'll be creating another branch for pikturr implementation, as previously discussed.

**Review by purplesmurf1998 — APPROVED** [review]
Ok implementing pikturr in a different branch is a good idea. In this case I'll approve this PR.

**Pull request merged**
