### PR TITLE
Admins can now modify zone perimeter paths

### PR DESCRIPTION
**Pull request by purplesmurf1998**
# Description
This pull request encompasses 2 user stories where the user can view locations assigned to a dealership and can also edit the zone's perimeter path after being created.
# How to Test
1. Log in and select a dealership
2. Scroll down to Dealership Zones section
3. Select a zone
4. Press on "Edit Zone Perimeter"
5. Drag points on the perimeter to edit the path
6. Click on "Save and Close"
# User Stories
[[AP-46] As a user, I would like to view geographical parking zones](https://soen390-team12.atlassian.net/browse/AP-46?atlOrigin=eyJpIjoiYzMzODQ0NGVmM2JkNDc3Mzk4NTY0YmU1NTk1NGE0YmYiLCJwIjoiaiJ9)
[[AP-47] As an administrator, I would like to edit geographical parking zones](https://soen390-team12.atlassian.net/browse/AP-47?atlOrigin=eyJpIjoiNmM2MGMyMjJkNmUwNDZmYWFlODE5ZDNmNjBhNjg4YzIiLCJwIjoiaiJ9)
# Screenshots
Screen Shot 2022-03-08 at 12 53 39 PM
Screen Shot 2022-03-08 at 12 53 54 PM
Screen Shot 2022-03-08 at 12 54 11 PM

### CODE REVIEW

**Review by AbdulSir — CHANGES_REQUESTED** [review]
In the dealership detail page, when staff account or vehicle property is not selected, the selected staff account detail, or the selected staff account detail title still appears. Maybe we can hide that for a more appeasing layout?

Let me know what do you think.

However, code wise, nothing to comment on. Code looks clean.

Screenshot:
image

**Comment by purplesmurf1998** [comment]
> In the dealership detail page, when staff account or vehicle property is not selected, the selected staff account detail, or the selected staff account detail title still appears. Maybe we can hide that for a more appeasing layout?
> 
> Let me know what do you think.
> 
> However, code wise, nothing to comment on. Code looks clean.
> 
> Screenshot: image

The titles were left there because they were meant to show that the details will appear there once selected. Since it's a pretty simple fix, I suggest we leave it like this and see how it passes in the second round of usability testing. If it's mentioned we can remove them.

**Comment by AbdulSir** [comment]
> > In the dealership detail page, when staff account or vehicle property is not selected, the selected staff account detail, or the selected staff account detail title still appears. Maybe we can hide that for a more appeasing layout?
> > Let me know what do you think.
> > However, code wise, nothing to comment on. Code looks clean.
> > Screenshot: image
> 
> The titles were left there because they were meant to show that the details will appear there once selected. Since it's a pretty simple fix, I suggest we leave it like this and see how it passes in the second round of usability testing. If it's mentioned we can remove them.

Sure, we can see how our testers will react to this and act accordingly.

**Review by AbdulSir — APPROVED** [review]

**Review by Emperor42 — COMMENTED** [review]
Code looks clean, very good

**Review by AnthonyChraim — APPROVED** [review]
Everything looks good from my end

**Pull request merged**
