### PR TITLE
Sprint 6 snapshot testing

### PR DESCRIPTION
**Pull request by AnthonyChraim**
Wrote some snapshot tests for the most important components.
Go to the frontend directory and run "npm run snaptest"
Some tests are failing for known reasons at the moment

### CODE REVIEW

**Review by AbdulSir — COMMENTED** [review]
I have ran the test using the command `npm run snaptest` and Im getting errors. Not sure if those errors are expected or not. Please review the below screenshot:

image

**Comment by AnthonyChraim** [comment]
> I have ran the test using the command `npm run snaptest` and Im getting errors. Not sure if those errors are expected or not. Please review the below screenshot:
> 
> image



> I have ran the test using the command `npm run snaptest` and Im getting errors. Not sure if those errors are expected or not. Please review the below screenshot:
> 
> image

Some tests are supposed to fail, but your output is not what I expected. Let's hop on a call later so we can further analyze the output

**Comment by AbdulSir** [comment]
I have created an issue #78 for the error that I'm getting. I don't think we can merge this PR until we fix the bug. However, I can see that a report is still being generated and many tests are passing.

**Comment by AnthonyChraim** [comment]
Okay, I will be closing the PR for now and re-open it once the bug is fixed

**Comment by AbdulSir** [comment]
> Okay, I will be closing the PR for now and re-open it once the bug is fixed

Okay sounds good.

**Pull request closed without merging**
